// API reference data for the docs site, read straight from the TypeScript source.
//
//   node scripts/api-docs.mjs            → site/generated/api.json + site/generated/tokens.json
//   node scripts/api-docs.mjs --stdout   → api.json to stdout (for a quick look)
//
// api.json: every component exported from src/index.ts (a capitalised export whose call
// signature takes one props object) with its props: name, type (as written in the source),
// required, default (JSDoc `@default`, else the destructuring default), description (JSDoc),
// deprecated. Props declared outside src/ (native DOM attributes, Base UI props) are not
// listed one by one; `extends` names where they come from.
//
// tokens.json: every `stylex.defineVars` / `defineConsts` group in src/tokens.stylex.ts with
// each token's light / dark value, JSDoc description and deprecated flag.
//
// No dependency beyond `typescript`, which is already a devDependency. The output is
// gitignored and regenerated by `pnpm site`, `pnpm site:build` and `pnpm site:test`.
import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, join, relative } from "node:path"
import { fileURLToPath } from "node:url"
import ts from "typescript"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const src = join(root, "src")

function createProgram(entries) {
	const configPath = join(root, "tsconfig.json")
	const config = ts.readConfigFile(configPath, ts.sys.readFile).config
	const { options } = ts.parseJsonConfigFileContent(config, ts.sys, root)
	return ts.createProgram(entries, { ...options, noEmit: true })
}

const docText = (checker, symbol) => ts.displayPartsToString(symbol.getDocumentationComment(checker)).trim()

function tagsOf(symbol, checker) {
	const tags = {}
	for (const tag of symbol.getJsDocTags(checker))
		tags[tag.name] = ts.displayPartsToString(tag.text ?? []).trim()
	return tags
}

const isOurs = (node) => !node.getSourceFile().fileName.includes("node_modules")

/** The function node behind a component export, to read destructuring defaults from. */
function functionNode(declaration) {
	if (ts.isFunctionDeclaration(declaration)) return declaration
	if (ts.isVariableDeclaration(declaration) && declaration.initializer) {
		const init = declaration.initializer
		if (ts.isArrowFunction(init) || ts.isFunctionExpression(init)) return init
	}
	return undefined
}

/** `DEFAULT_TIMEOUT` → `5000` when it names a module-level const with a literal value. */
function literalOf(node, checker) {
	if (ts.isIdentifier(node)) {
		const decl = checker.getSymbolAtLocation(node)?.valueDeclaration
		const init = decl && ts.isVariableDeclaration(decl) ? decl.initializer : undefined
		if (init && (ts.isLiteralExpression(init) || ts.isPrefixUnaryExpression(init))) return init.getText()
	}
	return node.getText()
}

/** `{ size = "md", variant = "primary" }` → { size: '"md"', variant: '"primary"' } */
function destructuringDefaults(fn, checker) {
	const defaults = {}
	const param = fn?.parameters[0]
	if (param == null || !ts.isObjectBindingPattern(param.name)) return defaults
	for (const element of param.name.elements) {
		if (element.initializer == null) continue
		const key = element.propertyName ?? element.name
		if (ts.isIdentifier(key)) defaults[key.text] = literalOf(element.initializer, checker)
	}
	return defaults
}

/** Where the props declared outside src come from, e.g. ["React.ButtonHTMLAttributes", "@base-ui/react"]. */
function externalBases(propsType) {
	const names = new Set()
	for (const prop of propsType.getProperties()) {
		const decl = prop.declarations?.[0]
		if (decl == null || isOurs(decl)) continue
		const owner = decl.parent
		const ownerName =
			owner && (ts.isInterfaceDeclaration(owner) || ts.isTypeAliasDeclaration(owner))
				? owner.name.text
				: owner?.parent && ts.isTypeAliasDeclaration(owner.parent)
					? owner.parent.name.text
					: undefined
		const file = decl.getSourceFile().fileName
		const pkg = file.includes("@types/react")
			? "react"
			: (file.match(/.*node_modules\/(@[^/]+\/[^/]+|[^/@.][^/]*)/)?.[1] ?? "external")
		names.add(ownerName ? `${pkg}:${ownerName}` : pkg)
	}
	// React's own attribute interfaces collapse to one line: the reader wants "native attributes".
	const react = [...names].filter((n) => n.startsWith("react"))
	const other = [...names].filter((n) => !n.startsWith("react"))
	const attrs = react.find((n) => /:(\w+)HTMLAttributes$/.test(n) && !/:(HTML|AllHTML)Attributes$/.test(n))
	const out = []
	if (react.length > 0) out.push(attrs ? attrs.replace("react:", "React.") : "React.HTMLAttributes")
	const basePkgs = new Set(other.map((n) => n.split(":")[0]))
	for (const pkg of basePkgs) out.push(pkg)
	return out
}

/**
 * The type as written in the source (`ReactNode`, not its expansion), unless it names something
 * the reader cannot import: a private alias (`Variant`) or `keyof typeof X` is expanded instead.
 */
function typeText(prop, checker, location, publicNames) {
	const decl = prop.declarations?.[0]
	const written =
		decl && (ts.isPropertySignature(decl) || ts.isPropertyDeclaration(decl)) && decl.type
			? decl.type.getText().replace(/\s+/g, " ")
			: undefined
	if (written != null) {
		const names = written.match(/\b[A-Z]\w*/g) ?? []
		const known = (n) => publicNames.has(n) || GLOBAL_TYPES.has(n)
		if (!written.includes("typeof") && names.every(known)) return written
	}
	const expanded = expandedType(prop, checker, location, publicNames)
	// `keyof JSX.IntrinsicElements` expands to a hundred tags; the source text says more.
	return expanded.length > 120 ? (written ?? "ReactNode") : expanded
}

function expandedType(prop, checker, location, publicNames) {
	const type = checker.getNonNullableType(checker.getTypeOfSymbolAtLocation(prop, location))
	const print = (t) => checker.typeToString(t, undefined, ts.TypeFormatFlags.NoTruncation)
	// A private union alias prints as its name; spell out its members instead.
	if (type.isUnion() && type.aliasSymbol && !publicNames.has(type.aliasSymbol.getName()))
		return type.types.map(print).join(" | ")
	return print(type)
}

// Types a reader knows without importing them from this package.
const GLOBAL_TYPES = new Set([
	"React",
	"JSX",
	"ReactNode",
	"ReactElement",
	"CSSProperties",
	"Ref",
	"RefObject",
	"Partial",
	"Record",
	"Promise",
	"Array",
	"ReadonlyArray",
	"File",
	"FileList",
	"Date",
	"HTMLElement",
	"HTMLInputElement",
	"HTMLTextAreaElement",
	"HTMLButtonElement",
	"HTMLDivElement",
	"KeyboardEvent",
	"MouseEvent",
	"ChangeEvent",
	"Error",
	"StyleArg",
	"StyleXStyles",
	"Omit",
	"Pick",
	"ComponentProps",
	"ComponentType",
	"Set",
	"Map",
	"AbortSignal",
	"Blob",
])

export function apiDocs() {
	const program = createProgram([join(src, "index.ts")])
	const checker = program.getTypeChecker()
	const index = program.getSourceFile(join(src, "index.ts"))
	const moduleSymbol = checker.getSymbolAtLocation(index)
	const components = []
	const publicNames = new Set(checker.getExportsOfModule(moduleSymbol).map((s) => s.getName()))

	for (const exported of checker.getExportsOfModule(moduleSymbol)) {
		const name = exported.getName()
		if (!/^[A-Z]/.test(name) || name.endsWith("Context")) continue
		const target = exported.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(exported) : exported
		if (!(target.flags & (ts.SymbolFlags.Function | ts.SymbolFlags.Variable))) continue
		const declaration = target.declarations?.[0]
		if (declaration == null) continue
		const type = checker.getTypeOfSymbolAtLocation(target, declaration)
		const signatures = type.getCallSignatures()
		if (signatures.length !== 1 || signatures[0].parameters.length > 1) continue
		const file = relative(root, declaration.getSourceFile().fileName)
		const folder = file.match(/^src\/components\/([^/]+)\//)?.[1]
		if (folder == null) continue

		// `export const Item = GroupItem`: an alias, documented on the original
		if (
			ts.isVariableDeclaration(declaration) &&
			declaration.initializer &&
			ts.isIdentifier(declaration.initializer)
		) {
			components.push({
				name,
				folder,
				file,
				aliasOf: declaration.initializer.text,
				description: docText(checker, target),
				deprecated: "deprecated" in tagsOf(target, checker),
				props: [],
			})
			continue
		}

		const signature = signatures[0]
		const param = signature.parameters[0]
		const propsType = param ? checker.getTypeOfSymbolAtLocation(param, declaration) : undefined
		const defaults = destructuringDefaults(functionNode(declaration), checker)
		const props = []
		for (const prop of propsType?.getProperties() ?? []) {
			const decl = prop.declarations?.[0]
			if (decl == null || !isOurs(decl)) continue
			const tags = tagsOf(prop, checker)
			props.push({
				name: prop.getName(),
				type: typeText(prop, checker, declaration, publicNames),
				required: !(prop.flags & ts.SymbolFlags.Optional),
				default: tags.default ?? defaults[prop.getName()] ?? null,
				description: docText(checker, prop),
				deprecated: "deprecated" in tags ? tags.deprecated || true : false,
			})
		}
		const tags = tagsOf(target, checker)
		const entry = {
			name,
			folder,
			file,
			description: docText(checker, target),
			deprecated: "deprecated" in tags ? tags.deprecated || true : false,
			extends: propsType ? externalBases(propsType, checker) : [],
			props,
		}
		components.push(entry)
	}
	components.sort((a, b) => a.folder.localeCompare(b.folder) || a.file.localeCompare(b.file))
	return { generatedFrom: "src/index.ts", components }
}

/** `{ default: "#fff", [DARK]: "#000" }` → { light, dark }; a string literal → { value }. */
function tokenValue(node) {
	if (ts.isStringLiteralLike(node)) return { value: node.text }
	if (ts.isNumericLiteral(node)) return { value: Number(node.text) }
	if (ts.isObjectLiteralExpression(node)) {
		const out = {}
		for (const p of node.properties) {
			if (!ts.isPropertyAssignment(p) || !ts.isStringLiteralLike(p.initializer)) continue
			const key = ts.isComputedPropertyName(p.name)
				? "dark"
				: p.name.getText() === "default"
					? "light"
					: p.name.getText()
			out[key] = p.initializer.text
		}
		return out
	}
	return { value: node.getText() }
}

export function tokenDocs() {
	const file = join(src, "tokens.stylex.ts")
	const program = createProgram([file])
	const checker = program.getTypeChecker()
	const source = program.getSourceFile(file)
	const groups = []
	for (const statement of source.statements) {
		if (!ts.isVariableStatement(statement)) continue
		for (const decl of statement.declarationList.declarations) {
			const call = decl.initializer
			if (call == null || !ts.isCallExpression(call)) continue
			const callee = call.expression.getText()
			if (callee !== "stylex.defineVars" && callee !== "stylex.defineConsts") continue
			const object = call.arguments[0]
			if (!ts.isObjectLiteralExpression(object)) continue
			const groupSymbol = checker.getSymbolAtLocation(decl.name)
			const groupTags = groupSymbol ? tagsOf(groupSymbol, checker) : {}
			const tokens = []
			for (const prop of object.properties) {
				if (!ts.isPropertyAssignment(prop)) continue
				const symbol = checker.getSymbolAtLocation(prop.name)
				const tags = symbol ? tagsOf(symbol, checker) : {}
				tokens.push({
					key: prop.name.getText(),
					...tokenValue(prop.initializer),
					description: symbol ? docText(checker, symbol) : "",
					deprecated: "deprecated" in tags ? tags.deprecated || true : false,
				})
			}
			groups.push({
				name: decl.name.getText(),
				kind: callee === "stylex.defineConsts" ? "consts" : "vars",
				description: groupSymbol ? docText(checker, groupSymbol) : "",
				deprecated: "deprecated" in groupTags ? groupTags.deprecated || true : false,
				tokens,
			})
		}
	}
	return { generatedFrom: "src/tokens.stylex.ts", groups }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
	const api = apiDocs()
	if (process.argv.includes("--stdout")) {
		process.stdout.write(`${JSON.stringify(api, null, "\t")}\n`)
	} else {
		const out = join(root, "site/generated")
		mkdirSync(out, { recursive: true })
		const tokens = tokenDocs()
		writeFileSync(join(out, "api.json"), `${JSON.stringify(api, null, "\t")}\n`)
		writeFileSync(join(out, "tokens.json"), `${JSON.stringify(tokens, null, "\t")}\n`)
		const props = api.components.reduce((n, c) => n + c.props.length, 0)
		console.log(`  api.json      ${api.components.length} components, ${props} props`)
		console.log(`  tokens.json   ${tokens.groups.length} groups`)
	}
}
