// dist/brand.css is generated from src/brand.css: one file that a one-off page without a bundler
// can pull in with <link>.
//
// None of the three things spliced in are copied by hand:
// - the Google Fonts @import (external pages have no @fontsource)
// - tokens.css inlined verbatim (no relative paths to worry about)
// - .ak-theme-light / .ak-theme-dark: manual themes copied from the light / dark blocks of tokens.css
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { declarations } from "./tokens-css.mjs"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")

const FONTS =
	'@import url("https://fonts.googleapis.com/css2?family=Figtree:wght@300..900&family=Geist+Mono:wght@100..900&family=Noto+Sans+TC:wght@100..900&display=swap");'

/** Write a declaration map back as CSS lines. oxfmt may fold a value onto several lines (fonts), so rebuild from the parsed Map instead of copying line by line. */
const lines = (decls) => [...decls].map(([name, value]) => `\t${name}: ${value};`).join("\n")

export function generate() {
	const src = readFileSync(join(root, "src/brand.css"), "utf8")
	const tokens = readFileSync(join(root, "src/tokens.css"), "utf8")
	const darkDecls = declarations(tokens, '[data-theme="dark"]')
	// The light theme only needs the values with a dark variant; :root already sets theme-agnostic ones like space and type
	const light = lines([...declarations(tokens, ":root")].filter(([name]) => darkDecls.has(name)))
	const dark = lines(darkDecls)

	const themes = `/* Manual themes: generated by scripts/brand-css.mjs */
/* Locks light by hand; on html it locks the whole page, on a subtree only that part. */
:root.ak-theme-light,
.ak-theme-light {
${light}
}
/* Locks dark by hand. */
:root.ak-theme-dark,
.ak-theme-dark {
${dark}
}`

	return src
		.replace("/* @import-fonts */", FONTS)
		.replace("/* @tokens */", tokens.trim())
		.replace("/* @themes */", themes)
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
	const out = join(root, "dist/brand.css")
	const css = generate()
	writeFileSync(out, css)
	console.log(`  brand.css       ${(Buffer.byteLength(css) / 1024).toFixed(1)} kB`)
}
