// The vocabularies of DESIGN.md and brand.css must stay in sync: every ak-* class the document
// mentions must exist in the css, and every class in the css must appear in the document at least
// once. Out of sync fails the check (part of pnpm check).
//
// The document explains judgment and the css defines the vocabulary. If they drift apart, either the
// document tells you to use a class that does not exist, or the css has a class nobody knows how to
// use. Both push an agent to invent its own, which is exactly what this system exists to prevent.
import { readFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")

/** Class names of all .ak-* selectors in brand.css (deduplicated, sorted). */
export function cssClasses(css = readFileSync(join(root, "src/brand.css"), "utf8")) {
	// Look at selectors only, not comments; abbreviations like `-warning` in a comment do not count
	const noComments = css.replace(/\/\*[\s\S]*?\*\//g, "")
	return [...new Set([...noComments.matchAll(/\.(ak-[\w-]+)/g)].map((m) => m[1]))].sort()
}

/** The ak-* names mentioned in DESIGN.md. */
export function docClasses(md = readFileSync(join(root, "DESIGN.md"), "utf8")) {
	// Skip --ak-* variables, and generic names ending in - such as `ak-grid-*`
	return [...new Set([...md.matchAll(/(?<![-\w])(ak-[\w-]*\w)/g)].map((m) => m[1]))]
		.filter((c) => !md.includes(`${c}-*`))
		.sort()
}

// ak-theme-* is generated by brand-css.mjs and absent from src/brand.css; the document mentions it and the check must count it
const GENERATED = ["ak-theme-light", "ak-theme-dark"]

if (process.argv[1] === fileURLToPath(import.meta.url)) {
	const css = new Set([...cssClasses(), ...GENERATED])
	const doc = new Set(docClasses())
	const missingInCss = [...doc].filter((c) => !css.has(c))
	const missingInDoc = [...css].filter((c) => !doc.has(c))
	if (missingInCss.length + missingInDoc.length === 0) {
		console.log(`  design-check    ${css.size} classes, DESIGN.md and brand.css in sync`)
	} else {
		for (const c of missingInCss) console.error(`  DESIGN.md mentions ${c}, brand.css does not have it`)
		for (const c of missingInDoc) console.error(`  brand.css has ${c}, DESIGN.md does not mention it`)
		process.exit(1)
	}
}
