// themes.stylex.ts is generated from tokens.stylex.ts.
//
// A hand-copied set of values will inevitably drift: a new group added to tokens but not to themes
// means that switching to light by hand changes only half of the values.
// This script serves both `pnpm gen:themes` and the themes test, so both run the same derivation.
import { readFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")

/** For every defineVars group in tokens.stylex.ts, its { key: [light, dark] } entries; groups with no dark variant are left out. */
export function readThemedGroups() {
	const source = readFileSync(join(root, "src/tokens.stylex.ts"), "utf8")
	const groups = []
	for (const group of source.matchAll(/export const (\w+) = stylex\.defineVars\(\{(.*?)\n\}\)/gs)) {
		const [, name, body] = group
		const vars = []
		for (const v of body.matchAll(/(\w+):\s*\{\s*default:\s*"([^"]*)",\s*\[DARK\]:\s*"([^"]*)",?\s*\}/g)) {
			vars.push({ key: v[1], light: v[2], dark: v[3] })
		}
		if (vars.length > 0) groups.push({ name, vars })
	}
	return groups
}

export function renderThemes(groups) {
	const imports = groups.map((g) => g.name).join(", ")
	const block = (mode) =>
		groups
			.map(
				(g) =>
					`export const ${mode}${cap(g.name)} = stylex.createTheme(${g.name}, {\n` +
					g.vars.map((v) => `\t${v.key}: "${v[mode]}",`).join("\n") +
					"\n})",
			)
			.join("\n\n")
	// The output is already in oxfmt format (the test compares it character by character)
	const names = (mode) => groups.map((g) => `${mode}${cap(g.name)}`).join(", ")
	return `// Generated by scripts/themes.mjs from tokens.stylex.ts. Do not edit by hand.
// Regenerate with pnpm gen:themes (themes.test.ts fails when it drifts).
//
// For apps where the user picks the theme (e.g. next-themes). Tokens follow the OS; applying a theme pins it.
// **Apply the whole set**: applying only color leaves shadows and tones on the other theme.
import * as stylex from "@stylexjs/stylex"
import { ${imports} } from "./tokens.stylex"

${block("light")}

${block("dark")}

/** Apply on the root element: \`<div {...stylex.props(...light)}>\` */
export const light = [${names("light")}] as const
export const dark = [${names("dark")}] as const
`
}

const cap = (s) => s[0].toUpperCase() + s.slice(1)

export const generate = () => renderThemes(readThemedGroups())
